//Board actions
const SET_BOARD = "SET_BOARD";
const SET_BOARD_RULES = "SET_BOARD_RULES";
const UPDATE_BOARD = "UPDATE_BOARD";
const RESET_BOARD = "RESET_BOARD";

//Player actions
const SET_TURN = "SET_TURN";
const SET_NEXT_TURN = "SET_NEXT_TURN";

export {
  SET_BOARD,
  SET_TURN,
  UPDATE_BOARD,
  SET_NEXT_TURN,
  SET_BOARD_RULES,
  RESET_BOARD
};
